import Foundation

extension PixelSpeciesCatalog {
    // MARK: - cat 小猫

    static func cat() -> PixelSpeciesDef {
        let base4 = SpeciesBase4(body: 0xFFFF_C178, dark: 0xFFE8_925A, light: 0xFFFF_F1DC, accent: 0xFFE8_925A)
        let sleepPose = [
            "................................",
            "................................",
            "................................",
            "................................",
            "........############............",
            "........############............",
            "....####OOOOOOOOOOOOOOOO####....",
            "....####OOOOOOOOOOOOOOOO####....",
            "..##ooooOOOOOOOOOOOOOOOOoooo##..",
            "..##ooooOOOOOOOOOOOOOOOOoooo##..",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOOOO####OOOOOOOO####OOOOOO##",
            "##OOOOOO####OOOOOOOO####OOOOOO##",
            "##OOOOOOOOOO++oooo++OOOOOOOOOO##",
            "##OOOOOOOOOO++oooo++OOOOOOOOOO##",
            "##OOOOooOOOOOOOOOOOOOOOOooOOOO##",
            "##OOOOooOOOOOOOOOOOOOOOOooOOOO##",
            "##OOOOooooooooooooooooooooOOOO##",
            "##OOOOooooooooooooooooooooOOOO##",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "....########################....",
            "....########################....",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let baby = [
            "................................",
            "................................",
            "......##............##..........",
            "......##............##..........",
            "....####............####........",
            "....####............####........",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OO##wwww##OOOO##wwww##OO##..",
            "..##OO##wwww##OOOO##wwww##OO##..",
            "..##OO##wwxx##OOOO##xxww##OO##..",
            "..##OO##wwxx##OOOO##xxww##OO##..",
            "..##OOOOOOOO++oooo++OOOOOOOO##..",
            "..##OOOOOOOO++oooo++OOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOO##....##OOOO##........",
            "....##OOOO##....##OOOO##........",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let child = [
            "................................",
            "................................",
            "................................",
            "................................",
            "....####............####........",
            "....####............####........",
            "..##oooo##........##oooo##......",
            "..##oooo##........##oooo##......",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##ooOOOOOOOOOOOOOOOOOOOOoo##..",
            "..##ooOOOOOOOOOOOOOOOOOOOOoo##..",
            "..##OO##wwww##OOOO##wwww##OO##..",
            "..##OO##wwww##OOOO##wwww##OO##..",
            "..##OO##wwxx##OOOO##xxww##OO##..",
            "..##OO##wwxx##OOOO##xxww##OO##..",
            "oo##OOOOOO++oooo++OOOOOOOO##oo..",
            "oo##OOOOOO++oooo++OOOOOOOO##oo..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOO++++++++++++OOOO##oo....",
            "..##OOOO++++++++++++OOOO##oo....",
            "..##OOOOOO++++++++OOOOOO##oo....",
            "..##OOOOOO++++++++OOOOOO##oo....",
            "....##OOOO##....##OOOO##..oo....",
            "....##OOOO##....##OOOO##..oo....",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let adult = [
            "................................",
            "................................",
            "....####............####........",
            "....####............####........",
            "..##oooo##........##oooo##......",
            "..##oooo##........##oooo##......",
            "..##OOOOoo##....##ooOOOO##......",
            "..##OOOOoo##....##ooOOOO##......",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##ooOOOOOOOOOOOOOOOOOOOOoo##..",
            "..##ooOOOOOOOOOOOOOOOOOOOOoo##..",
            "..##OO##wwww##OOOO##wwww##OO##..",
            "..##OO##wwww##OOOO##wwww##OO##..",
            "..##OO##wwxx##OOOO##xxww##OO##..",
            "..##OO##wwxx##OOOO##xxww##OO##..",
            "oo##OOOOOO++oooo++OOOOOOOO##oo..",
            "oo##OOOOOO++oooo++OOOOOOOO##oo..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOO##......",
            "..##OOOOOOOOOOOOOOOOOOOO##......",
            "..##OOOO++++++++++++OOOO##oo....",
            "..##OOOO++++++++++++OOOO##oo....",
            "..##OOOO++++++++++++OOOO##oooo..",
            "..##OOOO++++++++++++OOOO##oooo..",
            "..##OOOOOO++++++++OOOOOO##oooo..",
            "..##OOOOOO++++++++OOOOOO##oooo..",
            "....##OOOO##....##OOOO##..oo##..",
            "....##OOOO##....##OOOO##..oo##..",
            "................................",
            "................................",
        ]
        return assemble(id: "cat", nameZh: "小猫", base4: base4, stages: [
            ("baby", baby, Feat(mouthRow: 7, mouthCols: [6, 7], cheek: [(6, 3), (6, 4), (6, 11), (6, 12)], z: [(2, 13), (0, 13)], sweat: (4, 12)), sleepPose),
            ("child", child, Feat(mouthRow: 8, mouthCols: [6, 7], cheek: [(8, 3), (8, 4), (8, 11), (8, 12)], z: [(2, 14), (0, 14)], sweat: (4, 12)), sleepPose),
            ("adult", adult, Feat(mouthRow: 8, mouthCols: [6, 7], cheek: [(8, 3), (8, 4), (8, 11), (8, 12)], z: [(1, 14), (-1, 14)], sweat: (4, 12)), sleepPose),
        ])
    }
}
