import Foundation

extension PixelSpeciesCatalog {
    // MARK: - dog 小狗

    static func dog() -> PixelSpeciesDef {
        let base4 = SpeciesBase4(body: 0xFFC8_965A, dark: 0xFF8A_5A34, light: 0xFFF3_E2C4, accent: 0xFF4A_3020)
        let baby = [
            "................................",
            "................................",
            "........################........",
            "........################........",
            "....oo##OOOOOOOOOOOOOOOO##oo....",
            "....oo##OOOOOOOOOOOOOOOO##oo....",
            "..oooo##OOOOOOOOOOOOOOOO##oooo..",
            "..oooo##OOOOOOOOOOOOOOOO##oooo..",
            "..oooo##OOwwww####wwwwOO##oooo..",
            "..oooo##OOwwww####wwwwOO##oooo..",
            "..oooo##OOwwxx####xxwwOO##oooo..",
            "..oooo##OOwwxx####xxwwOO##oooo..",
            "..oooo##OOOOOOOOOOOOOOOO##oooo..",
            "..oooo##OOOOOOOOOOOOOOOO##oooo..",
            "......##OO++++++++++++OO##......",
            "......##OO++++++++++++OO##......",
            "......##OO++++^^^^++++OO##......",
            "......##OO++++^^^^++++OO##......",
            "......##OOOOOOOOOOOOOOOO##......",
            "......##OOOOOOOOOOOOOOOO##......",
            "......##OOOOOOOOOOOOOOOO##oo....",
            "......##OOOOOOOOOOOOOOOO##oo....",
            "......##OOOOOOOOOOOOOOOO##oooo..",
            "......##OOOOOOOOOOOOOOOO##oooo..",
            "......##oooo....oooo##..........",
            "......##oooo....oooo##..........",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let child = [
            "................................",
            "................................",
            "......####################......",
            "......####################......",
            "....oo##OOOOOOOOOOOOOOOO##oo....",
            "....oo##OOOOOOOOOOOOOOOO##oo....",
            "..oooo##OOOOOOOOOOOOOOOO##oooo..",
            "..oooo##OOOOOOOOOOOOOOOO##oooo..",
            "..oooo##OOwwww####wwwwOO##oooo..",
            "..oooo##OOwwww####wwwwOO##oooo..",
            "..oooo##OOwwxx####xxwwOO##oooo..",
            "..oooo##OOwwxx####xxwwOO##oooo..",
            "..oooo##OOOOOOOOOOOOOOOO##oooo..",
            "..oooo##OOOOOOOOOOOOOOOO##oooo..",
            "..oooo##OO++++++++++++OO##oooo..",
            "..oooo##OO++++++++++++OO##oooo..",
            "....oo##OO++++^^^^++++OO##oo....",
            "....oo##OO++++^^^^++++OO##oo....",
            "......##OOOO++++++++OOOO##......",
            "......##OOOO++++++++OOOO##......",
            "......##OOOOOOOOOOOOOOOO##oo....",
            "......##OOOOOOOOOOOOOOOO##oo....",
            "......##OOOOOOOOOOOOOOOO##oooo..",
            "......##OOOOOOOOOOOOOOOO##oooo..",
            "......##OOOOOOOOOOOOOOOO##......",
            "......##OOOOOOOOOOOOOOOO##......",
            "......##oooo##....##oooo##......",
            "......##oooo##....##oooo##......",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let adult = [
            "................................",
            "................................",
            "......####################......",
            "......####################......",
            "....oo##OOOOOOOOOOOOOOOO##oo....",
            "....oo##OOOOOOOOOOOOOOOO##oo....",
            "..oooo##OOOOOOOOOOOOOOOO##oooo..",
            "..oooo##OOOOOOOOOOOOOOOO##oooo..",
            "oooooo##OOwwww####wwwwOO##oooooo",
            "oooooo##OOwwww####wwwwOO##oooooo",
            "oooooo##OOwwxx####xxwwOO##oooooo",
            "oooooo##OOwwxx####xxwwOO##oooooo",
            "..oooo##OOOOOOOOOOOOOOOO##oooo..",
            "..oooo##OOOOOOOOOOOOOOOO##oooo..",
            "..oooo##OO++++++++++++OO##oooo..",
            "..oooo##OO++++++++++++OO##oooo..",
            "....oo##OO++++^^^^++++OO##oo....",
            "....oo##OO++++^^^^++++OO##oo....",
            "......##OOOO++++++++OOOO##......",
            "......##OOOO++++++++OOOO##......",
            "......##OOOOOOOOOOOOOOOO##oo....",
            "......##OOOOOOOOOOOOOOOO##oo....",
            "......##OOOOOOOOOOOOOOOO##oooo..",
            "......##OOOOOOOOOOOOOOOO##oooo..",
            "......##OOOOOOOOOOOOOOOO##oooo..",
            "......##OOOOOOOOOOOOOOOO##oooo..",
            "......##OOOOOOOOOOOOOOOO##......",
            "......##OOOOOOOOOOOOOOOO##......",
            "......##oooo##....##oooo##......",
            "......##oooo##....##oooo##......",
            "................................",
            "................................",
        ]
        return assemble(id: "dog", nameZh: "小狗", base4: base4, stages: [
            ("baby", baby, Feat(mouthRow: 9, mouthCols: [6, 7, 8, 9], cheek: [(6, 4), (6, 5), (6, 10), (6, 11)], z: [(2, 14), (0, 14)], sweat: (1, 12)), nil),
            ("child", child, Feat(mouthRow: 9, mouthCols: [6, 7, 8, 9], cheek: [(6, 4), (6, 5), (6, 10), (6, 11)], z: [(2, 14), (0, 14)], sweat: (1, 13)), nil),
            ("adult", adult, Feat(mouthRow: 9, mouthCols: [6, 7, 8, 9], cheek: [(6, 4), (6, 5), (6, 10), (6, 11)], z: [(2, 14), (0, 14)], sweat: (1, 13)), nil),
        ])
    }
}
