import Foundation

extension PixelSpeciesCatalog {
    // MARK: - slime 史莱姆

    static func slime() -> PixelSpeciesDef {
        let base4 = SpeciesBase4(body: 0xFFFF_93C0, dark: 0xFFE1_62A0, light: 0xFFFF_D2E6, accent: 0xFFFF_D2E6)
        let baby = [
            "................................",
            "................................",
            "................................",
            "................................",
            "..............##................",
            "..............##................",
            "............##++##..............",
            "............##++##..............",
            "..........##OO++OO##............",
            "..........##OO++OO##............",
            "........##OOOOOOOOOO##..........",
            "........##OOOOOOOOOO##..........",
            "......##OOOOOOOOOOOOOO##........",
            "......##OOOOOOOOOOOOOO##........",
            "....##OOOO##wwww##wwww##OO##....",
            "....##OOOO##wwww##wwww##OO##....",
            "....##OOOO##wwxx##xxww##OO##....",
            "....##OOOO##wwxx##xxww##OO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOO++oooo++OOOOOO##....",
            "....##OOOOOO++oooo++OOOOOO##....",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "....########################....",
            "....########################....",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let child = [
            "................................",
            "................................",
            "................................",
            "................................",
            "..............####..............",
            "..............####..............",
            "............##++++##............",
            "............##++++##............",
            "..........##OO++++OO##..........",
            "..........##OO++++OO##..........",
            "..........##OOOO++OO##..........",
            "..........##OOOO++OO##..........",
            "........##OOOOOOOOOOOO##........",
            "........##OOOOOOOOOOOO##........",
            "......##OOOOOOOOOOOOOOOO##......",
            "......##OOOOOOOOOOOOOOOO##......",
            "....##OOOO##wwww##wwww##OO##....",
            "....##OOOO##wwww##wwww##OO##....",
            "....##OOOO##wwxx##xxww##OO##....",
            "....##OOOO##wwxx##xxww##OO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOO++oooo++OOOOOO##....",
            "....##OOOOOO++oooo++OOOOOO##....",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "....########################....",
            "....########################....",
            "................................",
            "................................",
        ]
        let adult = [
            "................................",
            "................................",
            "..............####..............",
            "..............####..............",
            "............##++++##............",
            "............##++++##............",
            "............##++++##............",
            "............##++++##............",
            "..........##OO++++OO##..........",
            "..........##OO++++OO##..........",
            "..........##OOOO++OO##..........",
            "..........##OOOO++OO##..........",
            "........##OOOOOOOOOOOO##........",
            "........##OOOOOOOOOOOO##........",
            "......##OOOOOOOOOOOOOOOO##......",
            "......##OOOOOOOOOOOOOOOO##......",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "..##OOOO##wwww####wwww##OOOO##..",
            "..##OOOO##wwww####wwww##OOOO##..",
            "..##OOOO##wwxx####xxww##OOOO##..",
            "..##OOOO##wwxx####xxww##OOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOO++oooooooo++OOOOOO##..",
            "..##OOOOOO++oooooooo++OOOOOO##..",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
        ]
        return assemble(id: "slime", nameZh: "史莱姆", base4: base4, stages: [
            ("baby", baby, Feat(mouthRow: 10, mouthCols: [6, 7, 8, 9], cheek: [(9, 3), (9, 4), (9, 11), (9, 12)], z: [(3, 12), (1, 12)], sweat: (8, 13)), nil),
            ("child", child, Feat(mouthRow: 11, mouthCols: [6, 7, 8, 9], cheek: [(10, 3), (10, 4), (10, 11), (10, 12)], z: [(3, 12), (1, 12)], sweat: (8, 13)), nil),
            ("adult", adult, Feat(mouthRow: 12, mouthCols: [6, 7, 8, 9], cheek: [(11, 3), (11, 4), (11, 11), (11, 12)], z: [(2, 12), (0, 12)], sweat: (9, 13)), nil),
        ])
    }
}
