import Foundation

extension PixelSpeciesCatalog {
    // MARK: - hedgehog 小刺猬

    static func hedgehog() -> PixelSpeciesDef {
        let base4 = SpeciesBase4(body: 0xFFD8_A874, dark: 0xFF7A_5638, light: 0xFFF0_D8B4, accent: 0xFF54_3A22)
        let baby = [
            "..^^..^^..^^..^^..^^..^^..^^....",
            "..^^..^^..^^..^^..^^..^^..^^....",
            "oo^^oo^^oo^^oo^^oo^^oo^^oo^^oo..",
            "oo^^oo^^oo^^oo^^oo^^oo^^oo^^oo..",
            "..oooooooooooooooooooooooooooo..",
            "..oooooooooooooooooooooooooooo..",
            "..ooooOOOOOOOOOOOOOOOOOOOOoooo..",
            "..ooooOOOOOOOOOOOOOOOOOOOOoooo..",
            "..ooOO##wwww##OOOO##wwww##OOoo..",
            "..ooOO##wwww##OOOO##wwww##OOoo..",
            "..ooOO##wwxx##OOOO##xxww##OOoo..",
            "..ooOO##wwxx##OOOO##xxww##OOoo..",
            "..ooooOOOO++++++++++++OOOOoooo..",
            "..ooooOOOO++++++++++++OOOOoooo..",
            "....ooOOOO++++++++++++OOOOoo....",
            "....ooOOOO++++++++++++OOOOoo....",
            "......ooOOOO++^^^^++OOOOoo......",
            "......ooOOOO++^^^^++OOOOoo......",
            "..........oooo^^^^oooo..........",
            "..........oooo^^^^oooo..........",
            "..........##oo....oo##..........",
            "..........##oo....oo##..........",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let child = [
            "..^^..^^..^^..^^..^^..^^..^^..^^",
            "..^^..^^..^^..^^..^^..^^..^^..^^",
            "oo^^oo^^oo^^oo^^oo^^oo^^oo^^oo^^",
            "oo^^oo^^oo^^oo^^oo^^oo^^oo^^oo^^",
            "oooooooooooooooooooooooooooooooo",
            "oooooooooooooooooooooooooooooooo",
            "..oooooooooooooooooooooooooooo..",
            "..oooooooooooooooooooooooooooo..",
            "..ooOOOOOOOOOOOOOOOOOOOOOOOOoo..",
            "..ooOOOOOOOOOOOOOOOOOOOOOOOOoo..",
            "..ooOO##wwww##OOOO##wwww##OOoo..",
            "..ooOO##wwww##OOOO##wwww##OOoo..",
            "..ooOO##wwxx##OOOO##xxww##OOoo..",
            "..ooOO##wwxx##OOOO##xxww##OOoo..",
            "..ooooOOOO++++++++++++OOOOoooo..",
            "..ooooOOOO++++++++++++OOOOoooo..",
            "....ooOOOO++++^^^^++++OOOOoo....",
            "....ooOOOO++++^^^^++++OOOOoo....",
            "......oooooo^^^^^^^^oooooo......",
            "......oooooo^^^^^^^^oooooo......",
            "........##oooo....oooo##........",
            "........##oooo....oooo##........",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let adult = [
            "^^..^^..^^..^^..^^..^^..^^..^^..",
            "^^..^^..^^..^^..^^..^^..^^..^^..",
            "^^oo^^oo^^oo^^oo^^oo^^oo^^oo^^oo",
            "^^oo^^oo^^oo^^oo^^oo^^oo^^oo^^oo",
            "oooooooooooooooooooooooooooooooo",
            "oooooooooooooooooooooooooooooooo",
            "oooooooooooooooooooooooooooooooo",
            "oooooooooooooooooooooooooooooooo",
            "..ooOOOOOOOOOOOOOOOOOOOOOOOOoo..",
            "..ooOOOOOOOOOOOOOOOOOOOOOOOOoo..",
            "..ooOOOOOOOOOOOOOOOOOOOOOOOOoo..",
            "..ooOOOOOOOOOOOOOOOOOOOOOOOOoo..",
            "..ooOO##wwww##OOOO##wwww##OOoo..",
            "..ooOO##wwww##OOOO##wwww##OOoo..",
            "..ooOO##wwxx##OOOO##xxww##OOoo..",
            "..ooOO##wwxx##OOOO##xxww##OOoo..",
            "..ooooOOOO++++++++++++OOOOoooo..",
            "..ooooOOOO++++++++++++OOOOoooo..",
            "....ooOOOO++++^^^^++++OOOOoo....",
            "....ooOOOO++++^^^^++++OOOOoo....",
            "......oooooo^^^^^^^^oooooo......",
            "......oooooo^^^^^^^^oooooo......",
            "........##oooo....oooo##........",
            "........##oooo....oooo##........",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        return assemble(id: "hedgehog", nameZh: "小刺猬", base4: base4, stages: [
            ("baby", baby, Feat(mouthRow: 7, mouthCols: [6, 7, 8, 9], cheek: [(6, 3), (6, 4), (6, 11), (6, 12)], z: [(4, 15), (2, 15)], sweat: (3, 15)), nil),
            ("child", child, Feat(mouthRow: 7, mouthCols: [6, 7, 8, 9], cheek: [(6, 3), (6, 4), (6, 11), (6, 12)], z: [(5, 15), (3, 15)], sweat: (4, 15)), nil),
            ("adult", adult, Feat(mouthRow: 8, mouthCols: [6, 7, 8, 9], cheek: [(6, 2), (6, 13), (7, 2), (7, 13)], z: [(6, 15), (4, 15)], sweat: (5, 15)), nil),
        ])
    }
}
