import Foundation

extension PixelSpeciesCatalog {
    // MARK: - frog 小青蛙

    static func frog() -> PixelSpeciesDef {
        let base4 = SpeciesBase4(body: 0xFF83_CE63, dark: 0xFF4E_9B3A, light: 0xFFE7_F3C0, accent: 0xFF4E_9B3A)
        let baby = [
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            ".........www........www.........",
            "........wwxww......wwxww........",
            ".......#wLxxw#....#wLxxw#.......",
            ".......#wxxxw#....#wxxxw#.......",
            "........#wxwLO####OOwxw#........",
            ".........#LLLLOOOOOOOO#.........",
            "........#LLLLLLOOOOOOOO#........",
            ".......#LLLLLLLOOOOOOOOO#.......",
            "......#LLLLLLLLOOOOOOOOOO#......",
            "......#OLLLLLLOOOOOOOOOOO#......",
            "......#OOLLLLSSSSSSOOOOOO#......",
            "......#OOOOSSSSSSSSSSoooo#......",
            "......#OOOSSSSSSSSSSSSooo#......",
            ".......#OOSSSSSSSSSSSSoo#.......",
            "........#OSSSSSSSSSSSSo#........",
            ".........##SSSSSSSSSS##.........",
            "..........#OO######OO#..........",
            ".........#ODO#....#ODO#.........",
            "..........###......###..........",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let child = [
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "........###..........###........",
            ".......#www#........#www#.......",
            "......#wxxxw#......#wxxxw#......",
            "......#wLxxw#......#wLxxw#......",
            "......#OxxxO#......#OxxxO#......",
            ".......#LLLLL######OOOOO#.......",
            "........#LLLLLOOOOOOOOO#........",
            ".......#LLLLLLLOOOOOOOOO#.......",
            "......#LLLLLLLLOOOOOOOOOO#......",
            ".....#LLLLLLLLLOOOOOOOOOOO#.....",
            "....#OOLLLLLLLOOOOOOOOOOOOO#....",
            "....#OOOLLLLLOOOOOOOOOOOOOO#....",
            "....#OOOOOOSSSSSSSSSSooooOO#....",
            "....#OOOOOSSSSSSSSSSSSooooo#....",
            "....#OOOOSSSSSSSSSSSSSSoooo#....",
            ".....#OOOSSSSSSSSSSSSSSooo#.....",
            "......#OOSSSSdddddddSSSoo#......",
            ".......##OSdddddddddddo##.......",
            ".........###dddddddd###.........",
            ".......##OOO########OOO##.......",
            ".......#ODO#........#ODO#.......",
            ".......#####........#####.......",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let adult = [
            "................................",
            "................................",
            "................................",
            "................................",
            "........#..............#........",
            "......#www#..........#www#......",
            ".....#wwxww#........#wwxww#.....",
            ".....#wLxxw#........#wLxxw#.....",
            ".....#wxxxw#........#wxxxw#.....",
            ".....#OwwwL#........#OwwwO#.....",
            "......##LL#..######..#OO##......",
            "........#LL##LOOOOO##OO#........",
            "......##LLLLLLLOOOOOOOOO##......",
            ".....#LLLLLLLLLOOOOOOOOOOO#.....",
            "....#LLLLLLLLLLOOOOOOOOOOOO#....",
            "...#OLLLLLLLLLOOOOOOOOOOOOOO#...",
            "..#OOOLLLLLLLOOOOOOOOOOOOOOOO#..",
            "..#OOOOOLLLOOOSSSSOOOOOOOOOOO#..",
            "..#OOOOOOOSSSSSSSSSSSSooooOOO#..",
            "..#OOOOOOSSSSSSSSSSSSSSoooooO#..",
            "..#OOOOOSSSSSSSSSSSSSSSSooooo#..",
            "...#OOOOSSSSSSSSSSSSSSSSoooo#...",
            "....#OOOSSSSSSSSSSSSSSSSooo#....",
            ".....#OOSSSSdddddddddSSSoo#.....",
            "......###dddddddddddddd###......",
            ".........####dddddd####.........",
            "......###O#..######..#O###......",
            ".....#OODOO#........#OODOO#.....",
            "......#####..........#####......",
            "................................",
            "................................",
            "................................",
        ]
        return assemble(id: "frog", nameZh: "小青蛙", base4: base4, stages: [
            ("baby", baby, Feat(mouthRow: 11, mouthCols: [6, 7, 8, 9], cheek: [(9, 3), (9, 12)], z: [(3, 13), (1, 13)], sweat: (5, 13)), nil),
            ("child", child, Feat(mouthRow: 10, mouthCols: [6, 7, 8, 9], cheek: [(9, 3), (9, 12)], z: [(3, 13), (1, 13)], sweat: (5, 13)), nil),
            ("adult", adult, Feat(mouthRow: 11, mouthCols: [5, 6, 7, 8, 9, 10], cheek: [(10, 2), (10, 13)], z: [(3, 14), (1, 14)], sweat: (6, 13)), nil),
        ])
    }
}
