import Foundation

extension PixelSpeciesCatalog {
    // MARK: - dragon 小龙

    static func dragon() -> PixelSpeciesDef {
        let base4 = SpeciesBase4(body: 0xFFB4_9BF0, dark: 0xFF84_68CE, light: 0xFFF6_E1A8, accent: 0xFFF6_E1A8)
        let baby = [
            "................................",
            "................................",
            "................................",
            ".........###........###.........",
            "........#^^#........#^#.........",
            "........#^^^#......#^^^#........",
            "........#^^^#......#^^^#........",
            "........#^^^^######^^^^#........",
            "........##^^^^LOOO^^^^##........",
            "..........#LLLLLOOOOO#..........",
            ".........#LLLLLLOOOOOO#.........",
            "........#LLLLLLLOOOOOOO#........",
            "........#LLLxLLLOOOxOOO#........",
            ".......#LLLxLxLLOOxLxOOO#.......",
            ".......#OLLxxxLOOOxxxOOO#.......",
            ".......#OOOxxxOOOOxxxooO#.......",
            "......#OOOOOxOOOOOOxooooO#......",
            ".....#oOOOOOODOOODOooooooo#.....",
            ".....#ooOOOOOOOOOOOooooooo#.....",
            "......#oOOOOOOO++OOoooooo#......",
            ".......#oOOOOO++++Oooooo#.......",
            "........#oOOOO++++OOooo#........",
            ".........#OOO++++++OOo#.........",
            "..........#O++++++++O#..........",
            "..........#OO++++++OO#..........",
            "..........#OOO++++OOO#..........",
            "...........#OO++++OO#...........",
            "...........#OOO++OOO#...........",
            "...........#OOO##OOO#...........",
            "...........#^^#..#^^#...........",
            "................................",
            "................................",
        ]
        let child = [
            "................................",
            "........###...........###.......",
            ".......#^^#..........#^^#.......",
            ".......#^^#..........#^^#.......",
            ".......#^^^#........#^^^#.......",
            ".......#^^^#........#^^^#.......",
            ".......#^^^^#......#^^^^#.......",
            ".......###^^^######^^^###.......",
            "..........#LLLLOOOOOO#..........",
            ".........#LLLLLLOOOOOO#.........",
            "........#LLLLLLLOOOOOOO#........",
            "........#LLxLLLLOOOOxOO#........",
            ".......#LLxLxLLLOOOxLxOO#.......",
            "......#OOLxxxLLOOOOxxxOOO#......",
            ".....#oOOOxxxLOOOOOxxxoOOo#.....",
            ".....#DOOOOxOOOOOOOOxoooOD#.....",
            "....#DoOOOOOODOOODOOooooooD#....",
            "...#DoooOOOOOOOOOOOOoooooooD#...",
            "..#DDDDDOOOOOOO++OOoooooDDDDD#..",
            "...#DooooOOOOO++++OOoooooooD#...",
            "....#DoooOOOO++++++OooooooD#....",
            ".....#DooOOOO++++++OOooooD#.....",
            ".....#oDOOOO++++++++OOoODo#.....",
            "......#oOOO++++++++++OOOo#......",
            ".......#OOOO++++++++OOOO#.......",
            "........#OOOO++++++OOOO#........",
            ".........#OOO++++++OOO#.........",
            "..........#OOO++++OOO#..........",
            "...........#OOO++OOO#...........",
            "..........#OOO####OOO#..........",
            "...........^#^....^#^...........",
            "................................",
        ]
        let adult = [
            ".......###............###.......",
            ".......#^#............#^#.......",
            ".......#^^#..........#^^#.......",
            ".......#^^#..........#^^#.......",
            "......#^^^^#........#^^^^#......",
            "......#^^^^#........#^^^^#......",
            "......#^^^^#.######.#^^^^#......",
            "......###^^^#LLOOOO#^^^###......",
            ".........#LLLLLLOOOOOO#.........",
            "........#LLLLLLLOOOOOOO#........",
            "........#LLLLLLLOOOOOOO#........",
            ".......#LLLxLLLLOOOOxOOO#.......",
            "......#LLLxLxLLLOOOxLxOOO#......",
            "......#OLLxxxLLOOOOxxxOOOo#.....",
            ".....#OOOOxxxOOOOOOxxxooOO#.....",
            "....#DoOOOOxOOOOOOOOxoooooD#....",
            "...#DooOOOOOODOOODOooooooooD#...",
            "..#DoooOOOOOOOOOOOOooooooooo#...",
            "..#oooooOOOOOOO++OOoooooooooo#..",
            ".#DDDDDo#OOOOO++++Ooooo#oDDDDD#.",
            "..#oooo#.#OOOO++++Oooo#.#oooo#..",
            "..#Doooo#OOOO++++++Oooo#oooo#...",
            "...#DoooOOOO++++++++OooooooD#...",
            "....#DooOOO++++++++++OOOooD#....",
            ".....#DOOOO++++++++++OOOOD#.....",
            "......#oOOO++++++++++OOOoo#.....",
            "......#oOOOO++++++++OOOOo#......",
            ".......##OOOO++++++OOOO##.......",
            ".........#OOOO++++OOOO#.........",
            ".........#OOOO++++OOOO#.........",
            ".........#OOOOO++OOOOO#.........",
            ".........#^#^######^#^#.........",
        ]
        return assemble(id: "dragon", nameZh: "小龙", base4: base4, stages: [
            ("baby", baby, Feat(mouthRow: 9, mouthCols: [7, 8], cheek: [(8, 4), (8, 11)], z: [(3, 13), (1, 13)], sweat: (4, 12), pawL: (11, 4), pawR: (11, 11), feetRow: 14), nil),
            ("child", child, Feat(mouthRow: 9, mouthCols: [7, 8], cheek: [(8, 3), (8, 12)], z: [(3, 13), (1, 13)], sweat: (4, 12), pawL: (12, 4), pawR: (12, 11), feetRow: 15), nil),
            ("adult", adult, Feat(mouthRow: 9, mouthCols: [6, 7, 8, 9], cheek: [(8, 3), (8, 12)], z: [(2, 13), (0, 13)], sweat: (4, 12), pawL: (12, 4), pawR: (12, 11), feetRow: 15), nil),
        ])
    }
}
