import Foundation

extension PixelSpeciesCatalog {
    // MARK: - rabbit 小兔

    static func rabbit() -> PixelSpeciesDef {
        let base4 = SpeciesBase4(body: 0xFFF2_EEE8, dark: 0xFFCB_C0B6, light: 0xFFFF_FFF4, accent: 0xFFF7_A8C0)
        let baby = [
            "........##^^##....##^^##........",
            "........##^^##....##^^##........",
            "........##^^##....##^^##........",
            "........##^^##....##^^##........",
            "........##OO##....##OO##........",
            "........##OO##....##OO##........",
            "......##OOOOOOOOOOOOOOOO##......",
            "......##OOOOOOOOOOOOOOOO##......",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOwwww####wwwwOOOO##....",
            "....##OOOOwwww####wwwwOOOO##....",
            "....##OOOOwwxx####xxwwOOOO##....",
            "....##OOOOwwxx####xxwwOOOO##....",
            "....##OOOOOOOO^^^^OOOOOOOO##....",
            "....##OOOOOOOO^^^^OOOOOOOO##....",
            "......##OOOO++++++++OOOO##......",
            "......##OOOO++++++++OOOO##......",
            "......##OOOOOOOOOOOOOOOO##......",
            "......##OOOOOOOOOOOOOOOO##......",
            "......##OOOOOOOOOOOOOOOO##oo....",
            "......##OOOOOOOOOOOOOOOO##oo....",
            "......##OOOO##....##OOOO##......",
            "......##OOOO##....##OOOO##......",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let child = [
            "........##^^##....##^^##........",
            "........##^^##....##^^##........",
            "........##^^##....##^^##........",
            "........##^^##....##^^##........",
            "........##^^##....##^^##........",
            "........##^^##....##^^##........",
            "........##OO##....##OO##........",
            "........##OO##....##OO##........",
            "......##OOOOOOOOOOOOOOOO##......",
            "......##OOOOOOOOOOOOOOOO##......",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOwwww####wwwwOOOO##....",
            "....##OOOOwwww####wwwwOOOO##....",
            "....##OOOOwwxx####xxwwOOOO##....",
            "....##OOOOwwxx####xxwwOOOO##....",
            "....##OOOOOOOO^^^^OOOOOOOO##....",
            "....##OOOOOOOO^^^^OOOOOOOO##....",
            "....##OOOOOO++++++++OOOOOO##....",
            "....##OOOOOO++++++++OOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##oo..",
            "....##OOOOOOOOOOOOOOOOOOOO##oo..",
            "....##OOOO##OOOOOOOO##OOOO##....",
            "....##OOOO##OOOOOOOO##OOOO##....",
            "......##OOOO##....##OOOO##......",
            "......##OOOO##....##OOOO##......",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let adult = [
            "........##^^##....##^^##........",
            "........##^^##....##^^##........",
            "........##^^##....##^^##........",
            "........##^^##....##^^##........",
            "........##^^##....##^^##........",
            "........##^^##....##^^##........",
            "........##OO##....##OO##........",
            "........##OO##....##OO##........",
            "......##OOOOOOOOOOOOOOOO##......",
            "......##OOOOOOOOOOOOOOOO##......",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOwwww##....##wwwwOOOO##..",
            "..##OOOOwwww##....##wwwwOOOO##..",
            "..##OOOOwwxx##....##xxwwOOOO##..",
            "..##OOOOwwxx##....##xxwwOOOO##..",
            "..##OOOOOOOO^^^^^^^^OOOOOOOO##..",
            "..##OOOOOOOO^^^^^^^^OOOOOOOO##..",
            "..##OOOOOO++++++++++++OOOOOO##..",
            "..##OOOOOO++++++++++++OOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "....##OOOOOOOOOOOOOOOOOOOO##oo..",
            "....##OOOOOOOOOOOOOOOOOOOO##oo..",
            "....##OOOO##OOOOOOOO##OOOO##....",
            "....##OOOO##OOOOOOOO##OOOO##....",
            "....##OOOO##........##OOOO##....",
            "....##OOOO##........##OOOO##....",
            "................................",
            "................................",
        ]
        return assemble(id: "rabbit", nameZh: "小兔", base4: base4, stages: [
            ("baby", baby, Feat(mouthRow: 8, mouthCols: [6, 7, 8, 9], cheek: [(6, 3), (6, 4), (6, 11), (6, 12)], z: [(2, 13), (0, 13)], sweat: (3, 13)), nil),
            ("child", child, Feat(mouthRow: 9, mouthCols: [6, 7, 8, 9], cheek: [(7, 3), (7, 4), (7, 11), (7, 12)], z: [(2, 13), (0, 13)], sweat: (4, 13)), nil),
            ("adult", adult, Feat(mouthRow: 10, mouthCols: [6, 7, 8, 9], cheek: [(7, 2), (7, 3), (7, 12), (7, 13)], z: [(2, 13), (0, 13)], sweat: (5, 13)), nil),
        ])
    }
}
