import Foundation

extension PixelSpeciesCatalog {
    // MARK: - slime 史莱姆

    static func slime() -> PixelSpeciesDef {
        let base4 = SpeciesBase4(body: 0xFFFF_93C0, dark: 0xFFE1_62A0, light: 0xFFFF_D2E6, accent: 0xFFFF_D2E6)
        let baby = [
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            ".............######.............",
            ".............#OOOO#.............",
            "............#OOOOOO#............",
            "............#OOOOOO#............",
            "............#OOOOOO#............",
            "...........#LLOOOOOO#...........",
            "..........#OOLLOOOOOO#..........",
            ".........#OOwOLLOOOwOO#.........",
            "........#OOwwwOLLOwwwOO#........",
            ".......#OOOwLxOLLOxLwOOO#.......",
            ".......#OOOwxxOLLOxxwOOO#.......",
            ".......#OOOOwOOOOOOwOOOO#.......",
            "......#OOOOOOOOOOOOOooooo#......",
            ".......#OOOOOOOOOOoooooo#.......",
            ".......#OOOOOOOOOOoooooo#.......",
            ".......#OOOOOOOOOooooooo#.......",
            "........#OOOOOOOOoooooo#........",
            ".........#OOOooooooooo#.........",
            "..........#oooooooooo#..........",
            "...........##########...........",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let child = [
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "..............####..............",
            "............##OOOO##............",
            "............#OOOOOO#............",
            "...........#OOOOOOOO#...........",
            "...........#OOOOOOOO#...........",
            "...........#OOOOOOOO#...........",
            "...........#OOOOOOOO#...........",
            "...........#LOOOOOOO#...........",
            "..........#OLLOOOOOOO#..........",
            "........##OOwLLOOOOwOO##........",
            ".......#OOOwwwLLOOwwwOOO#.......",
            "......#OOOOwLxLLOOxLwOOOO#......",
            "......#OOOOwxxLLOOxxwOOOO#......",
            ".....#OOOOOOwOOOOOOwOOOOOO#.....",
            ".....#OOOOOOOOOOOOOOOOOOOO#.....",
            ".....#OOOOOOOOOOOOOOOOoooo#.....",
            ".....#OOOOOOOOOOOOOOOooooo#.....",
            ".....#OOOOOOOOOOOOOooooooo#.....",
            "......#OOOOOOOOOOOOoooooo#......",
            "......#OOOOOOOOOOOooooooo#......",
            ".......#OOOOOOOOOOoooooo#.......",
            "........##Oooooooooooo##........",
            "..........##oooooooo##..........",
            "............########............",
            "................................",
            "................................",
            "................................",
        ]
        let adult = [
            "................................",
            "................................",
            "................................",
            "................................",
            "..............####..............",
            "............##OOOO##............",
            "............#OOOOOO#............",
            "...........#OOOOOOOO#...........",
            "...........#OOOOOOOO#...........",
            "..........#OOOOOOOOOO#..........",
            "..........#OOOOOOOOOO#..........",
            "..........#OOOOOOOOOO#..........",
            "..........#OLOOOOOOOO#..........",
            ".........#OOLOOOOOOOOO#.........",
            "........#OOOLOLOOOOOOOO#........",
            "......##OOOOwOLOOOOwOOOO##......",
            ".....#OOOOOwwwLLOOwwwOOOOO#.....",
            ".....#OOOOOwLxLOOOxLwOOOOO#.....",
            "....#OOOOOOwxxOOOOxxwOOOOOO#....",
            "....#OOOOOOOwOOOOOOwOOOOOOO#....",
            "....#OOOOOOOOOOOOOOOOOOOOOO#....",
            "...#OOOOOOOOOOOOOOOOOOOOoooo#...",
            "....#OOOOOOOOOOOOOOOOOooooo#....",
            "....#OOOOOOOOOOOOOOOOoooooo#....",
            "....#OOOOOOOOOOOOOOOooooooo#....",
            ".....#OOOOOOOOOOOOOooooooo#.....",
            ".....#OOOOOOOOOOOOOooooooo#.....",
            "......##OOOOOOOOOOOooooo##......",
            "........#oooooooooooooo#........",
            ".........###oooooooo###.........",
            "............########............",
            "................................",
        ]
        return assemble(id: "slime", nameZh: "史莱姆", base4: base4, stages: [
            ("baby", baby, Feat(mouthRow: 9, mouthCols: [7, 8], cheek: [(9, 4), (9, 11)], z: [(3, 12), (1, 12)], sweat: (8, 13), pawL: (11, 4), pawR: (11, 11), feetRow: 12), nil),
            ("child", child, Feat(mouthRow: 10, mouthCols: [6, 7, 8, 9], cheek: [(9, 3), (9, 12)], z: [(3, 12), (1, 12)], sweat: (9, 13), pawL: (12, 4), pawR: (12, 11), feetRow: 14), nil),
            ("adult", adult, Feat(mouthRow: 11, mouthCols: [6, 7, 8, 9], cheek: [(10, 3), (10, 12)], z: [(2, 12), (0, 12)], sweat: (10, 13), pawL: (13, 4), pawR: (13, 11), feetRow: 15), nil),
        ])
    }
}
