import Foundation

extension PixelSpeciesCatalog {
    // MARK: - goldfish 小金鱼

    static func goldfish() -> PixelSpeciesDef {
        let base4 = SpeciesBase4(body: 0xFFFF_8A3C, dark: 0xFFE8_5A28, light: 0xFFFF_D9A0, accent: 0xFFA9_E4F0)
        let baby = [
            "................................",
            "................................",
            "........^^^^^^^^^^^^^^..........",
            "........^^^^^^^^^^^^^^..........",
            "....^^^^OOOOOOOOOOOO^^^^........",
            "....^^^^OOOOOOOOOOOO^^^^........",
            "..^^^^OOOOOOOOOOOOOOOO^^^^......",
            "..^^^^OOOOOOOOOOOOOOOO^^^^......",
            "..^^OOOO##wwww##wwww##OOOO^^....",
            "..^^OOOO##wwww##wwww##OOOO^^....",
            "..^^OOOO##wwxx##xxww##OOOO^^....",
            "..^^OOOO##wwxx##xxww##OOOO^^....",
            "..^^ooOOOOOOOOOOOOOOOOoo^^......",
            "..^^ooOOOOOOOOOOOOOOOOoo^^......",
            "....^^OOOO++++++++OOOO^^........",
            "....^^OOOO++++++++OOOO^^........",
            "......^^OOOOOOOOOOOO^^..........",
            "......^^OOOOOOOOOOOO^^..........",
            "......^^^^ooOOOOoo^^^^..........",
            "......^^^^ooOOOOoo^^^^..........",
            "........^^^^^^^^^^^^............",
            "........^^^^^^^^^^^^............",
            "..........oooooooo..............",
            "..........oooooooo..............",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let child = [
            "................................",
            "................................",
            "........^^^^^^^^^^^^^^..........",
            "........^^^^^^^^^^^^^^..........",
            "....^^^^OOOOOOOOOOOOOOOO^^^^....",
            "....^^^^OOOOOOOOOOOOOOOO^^^^....",
            "..^^^^OOOOOOOOOOOOOOOOOOOO^^^^..",
            "..^^^^OOOOOOOOOOOOOOOOOOOO^^^^..",
            "..^^OOOO##wwww##wwww##OOOOOO^^..",
            "..^^OOOO##wwww##wwww##OOOOOO^^..",
            "..^^OOOO##wwxx##xxww##OOOOOO^^..",
            "..^^OOOO##wwxx##xxww##OOOOOO^^..",
            "..^^ooOOOOOOOOOOOOOOOOOOOOoo^^..",
            "..^^ooOOOOOOOOOOOOOOOOOOOOoo^^..",
            "..^^OOOOOO++++++++++++OOOOOO^^..",
            "..^^OOOOOO++++++++++++OOOOOO^^..",
            "....^^OOOOOO++++++++OOOOOO^^....",
            "....^^OOOOOO++++++++OOOOOO^^....",
            "....^^^^OOOOOOOOOOOOOOOO^^^^....",
            "....^^^^OOOOOOOOOOOOOOOO^^^^....",
            "......^^^^ooOOOOOOOOoo^^^^......",
            "......^^^^ooOOOOOOOOoo^^^^......",
            "........^^^^^^^^^^^^^^^^........",
            "........^^^^^^^^^^^^^^^^........",
            "..........oooooooooooo..........",
            "..........oooooooooooo..........",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let adult = [
            "................................",
            "................................",
            "......^^^^^^^^^^^^^^^^^^........",
            "......^^^^^^^^^^^^^^^^^^........",
            "..^^^^OOOOOOOOOOOOOOOOOOOO^^^^..",
            "..^^^^OOOOOOOOOOOOOOOOOOOO^^^^..",
            "..^^OOOOOOOOOOOOOOOOOOOOOOOO^^..",
            "..^^OOOOOOOOOOOOOOOOOOOOOOOO^^..",
            "^^^^OOOO##wwww##wwww##OOOOOO^^^^",
            "^^^^OOOO##wwww##wwww##OOOOOO^^^^",
            "^^^^OOOO##wwxx##xxww##OOOOOO^^^^",
            "^^^^OOOO##wwxx##xxww##OOOOOO^^^^",
            "^^^^ooOOOOOOOOOOOOOOOOOOOOoo^^^^",
            "^^^^ooOOOOOOOOOOOOOOOOOOOOoo^^^^",
            "^^^^OOOOOO++++++++++++OOOOOO^^^^",
            "^^^^OOOOOO++++++++++++OOOOOO^^^^",
            "..^^OOOOOO++++++++++++OOOOOO^^..",
            "..^^OOOOOO++++++++++++OOOOOO^^..",
            "..^^^^OOOOOOOOOOOOOOOOOOOO^^^^..",
            "..^^^^OOOOOOOOOOOOOOOOOOOO^^^^..",
            "....^^^^ooOOOOOOOOOOOOoo^^^^....",
            "....^^^^ooOOOOOOOOOOOOoo^^^^....",
            "......^^^^^^^^^^^^^^^^^^^^......",
            "......^^^^^^^^^^^^^^^^^^^^......",
            "....oo....oooooooooooo....oo....",
            "....oo....oooooooooooo....oo....",
            "......oooo............oooo......",
            "......oooo............oooo......",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        return assemble(id: "goldfish", nameZh: "小金鱼", base4: base4, stages: [
            ("baby", baby, Feat(mouthRow: 7, mouthCols: [6, 7, 8], cheek: [(6, 3), (6, 4), (6, 10), (6, 11)], z: [(2, 13), (0, 13)], sweat: (1, 12)), nil),
            ("child", child, Feat(mouthRow: 7, mouthCols: [6, 7, 8], cheek: [(6, 3), (6, 4), (6, 11), (6, 12)], z: [(2, 14), (0, 14)], sweat: (1, 12)), nil),
            ("adult", adult, Feat(mouthRow: 7, mouthCols: [6, 7, 8, 9], cheek: [(6, 3), (6, 4), (6, 11), (6, 12)], z: [(1, 13), (0, 13)], sweat: (1, 12)), nil),
        ])
    }
}
