import Foundation

extension PixelSpeciesCatalog {
    // MARK: - bird 小鸟

    static func bird() -> PixelSpeciesDef {
        let base4 = SpeciesBase4(body: 0xFFFF_D24A, dark: 0xFFE0_A028, light: 0xFFFF_F0BE, accent: 0xFF5C_9FE2)
        let baby = [
            "................................",
            "................................",
            "........############............",
            "........############............",
            "......##OOOOOOOOOOOOOOOO##......",
            "......##OOOOOOOOOOOOOOOO##......",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOwwww####wwwwOOOO##....",
            "....##OOOOwwww####wwwwOOOO##....",
            "....##OOOOwwxx####xxwwOOOO##....",
            "....##OOOOwwxx####xxwwOOOO##....",
            "....##OO^^OOOOooooOOOO^^OO##....",
            "....##OO^^OOOOooooOOOO^^OO##....",
            "....##OO^^OO++++++++OO^^OO##....",
            "....##OO^^OO++++++++OO^^OO##....",
            "......##^^OO++++++++OO^^##......",
            "......##^^OO++++++++OO^^##......",
            "......##OOOOOOOOOOOOOOOO##......",
            "......##OOOOOOOOOOOOOOOO##......",
            "........##OOOOOOOOOOOO##........",
            "........##OOOOOOOOOOOO##........",
            "..........oo##....##oo..........",
            "..........oo##....##oo..........",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let child = [
            "................................",
            "................................",
            "......####################......",
            "......####################......",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOwwww####wwwwOOOOOO##..",
            "..##OOOOOOwwww####wwwwOOOOOO##..",
            "..##OOOOOOwwxx####xxwwOOOOOO##..",
            "..##OOOOOOwwxx####xxwwOOOOOO##..",
            "..##OO^^OOOOOOooooOOOOOO^^OO##..",
            "..##OO^^OOOOOOooooOOOOOO^^OO##..",
            "..##OO^^OOOO++++++++OOOO^^OO##..",
            "..##OO^^OOOO++++++++OOOO^^OO##..",
            "..##OO^^OOOO++++++++OOOO^^OO##..",
            "..##OO^^OOOO++++++++OOOO^^OO##..",
            "..##OO^^OOOOOOOOOOOOOOOO^^OO##..",
            "..##OO^^OOOOOOOOOOOOOOOO^^OO##..",
            "....##OOOO++++++++++++OOOO##....",
            "....##OOOO++++++++++++OOOO##....",
            "......##OOOOOOOOOOOOOOOO##......",
            "......##OOOOOOOOOOOOOOOO##......",
            "........oo##....##oo............",
            "........oo##....##oo............",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let adult = [
            "................................",
            "................................",
            "......####################......",
            "......####################......",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "^^^^##OOOOwwww####wwwwOOOO##^^^^",
            "^^^^##OOOOwwww####wwwwOOOO##^^^^",
            "^^^^##OOOOwwxx####xxwwOOOO##^^^^",
            "^^^^##OOOOwwxx####xxwwOOOO##^^^^",
            "^^^^##OOOOOOOOooooOOOOOOOO##^^^^",
            "^^^^##OOOOOOOOooooOOOOOOOO##^^^^",
            "^^^^##OOOO++++++++++++OOOO##^^^^",
            "^^^^##OOOO++++++++++++OOOO##^^^^",
            "^^^^##OOOO++++++++++++OOOO##^^^^",
            "^^^^##OOOO++++++++++++OOOO##^^^^",
            "^^^^##OOOOOO++++++++OOOOOO##^^^^",
            "^^^^##OOOOOO++++++++OOOOOO##^^^^",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "........oo##....##oo............",
            "........oo##....##oo............",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        return assemble(id: "bird", nameZh: "小鸟", base4: base4, stages: [
            ("baby", baby, Feat(mouthRow: 7, mouthCols: [6, 7, 8, 9], cheek: [(5, 3), (5, 12), (6, 3), (6, 12)], z: [(2, 13), (0, 13)], sweat: (1, 12)), nil),
            ("child", child, Feat(mouthRow: 7, mouthCols: [6, 7, 8, 9], cheek: [(5, 3), (5, 12), (6, 4), (6, 11)], z: [(2, 14), (0, 14)], sweat: (1, 13)), nil),
            ("adult", adult, Feat(mouthRow: 7, mouthCols: [6, 7, 8, 9], cheek: [(5, 4), (5, 11), (6, 4), (6, 11)], z: [(2, 14), (0, 14)], sweat: (1, 13)), nil),
        ])
    }
}
