import Foundation

extension PixelSpeciesCatalog {
    // MARK: - cat 小猫

    static func cat() -> PixelSpeciesDef {
        let base4 = SpeciesBase4(body: 0xFFFF_C178, dark: 0xFFE8_925A, light: 0xFFFF_F1DC, accent: 0xFFE8_925A)
        let sleepPose = [
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "......#.....#...................",
            ".....#S#...#S#..................",
            ".....#S#...#S#..................",
            "....#SSS#.#SSS#.................",
            "....#SSSL#LSSS#.................",
            "...#OSSSLLLLSSO#................",
            "....#OLLLLLLOOOO#####...........",
            "....#O#LLLL#OOOOOOOOO###........",
            "...#OOO####OOOOOOOOOOOOO##......",
            "....#OOOOOOOOOOOOOOOOOOOOO#.....",
            "....#OOOOOOOOOOOOOOOOOOOOOO#....",
            "...#OOOOOOOOOOOOOOOoooooSOOO#...",
            "...#OOOOOOOOOOOOOooooSSSSSSS#...",
            "..#OOOOOOOOOOOOOooooSSdddddSS#..",
            "...#OOOOOOOOOOOooooSSdddddddS#..",
            "...#OOOOOOOOOOOoooooSSdddddS#...",
            "....#OOOOOOOOOOooooooSSSSSS#....",
            ".....#OOOOOOOOOOooooooooSo#.....",
            "......##OOOOOOOOOooooooo##......",
            "........###OOOOOOOOoo###........",
            "...........##########...........",
            "................................",
            "................................",
            "................................",
        ]
        let baby = [
            "................................",
            "................................",
            "................................",
            ".........#............#.........",
            "........#O#..........#O#........",
            "........#S#..........#S#........",
            ".......#SSS#.######.#SSS#.......",
            "......#OSSSL#LOOOOO#OSSSO#......",
            "......###SSSLLLOOOOOSSS###......",
            ".........#LLLLLLOOOOOO#.........",
            "........#LLLLLLLOOOOOOO#........",
            "........#LLLxLLLOOOxOOO#........",
            ".......#LLLLxxLLOOxxLOOO#.......",
            ".......#OLLxxxLOOOxxxOOO#.......",
            ".......#OOLxLxOOOOxLxOOO#.......",
            "........#OOOxOOOOOOxooo#........",
            "........#OOOOODDDOOoooo#........",
            ".........#OOOOODOOOooo#..#......",
            "..........#OOOODOOOoo#..#O#.....",
            "...........#OOOOOOOo#...#O#.....",
            "............#OOOOOO#....#O#.....",
            "...........#OOOOOOOO#..#OOO#....",
            "...........#OOSSSSOO#...#O#.....",
            "..........#OOSSSSSSOO#..#O#.....",
            "..........#OOSSSSSSOOO##OO#.....",
            "..........#OSSSSSSSSOOOOO#......",
            "...........#OSSSSSSOO#####......",
            "...........#OSSSSSSO#...........",
            "...........#SSSSSSSS#...........",
            "...........#SSS##SSS#...........",
            "...........####..####...........",
            "................................",
        ]
        let child = [
            "................................",
            "................................",
            "........#..............#........",
            ".......#O#............#O#.......",
            ".......#S#............#S#.......",
            "......#SSS#..######..#SSS#......",
            ".....#OSSSL##LOOOOO##OSSSO#.....",
            ".....#SSSSSLLLLOOOOOOSSSSS#.....",
            "....####SSSLLLLLOOOOOSSS####....",
            "........#LLLLLLLOOOOOOO#........",
            "........#LLxLLLLOOOOxOO#........",
            ".......#LLLxxLLLOOOxxLOO#.......",
            ".......#OLxxxLLOOOOxxxOO#.......",
            ".......#OOxLxLOOOOOxLxOO#.......",
            "........#OOxOOOOOOOOxoo#..##....",
            "........#OOOOODDDOOOooo#..##....",
            ".........#OOOOODOOOOoo#..#oo#...",
            "..........#OOOODOOOoo#...#oo#...",
            "...........#OOOOOOOo#....#oo#...",
            "..........#OOOOOOOOOo#...#oo#...",
            "..........#OOOSSSSOOo#..#Ooo#...",
            ".........#OOOSSSSSSOOo##OOo#....",
            ".........#OOSSSSSSSSoooOOOO#....",
            ".........#OOSSSSSSSSooo#o##.....",
            ".........#OOSSSSSSSSoo#.#.......",
            ".........#OOSSdddddSoo#.........",
            "..........#OSdddddddo#..........",
            "..........#OSdddddddo#..........",
            "...........#OSdddddo#...........",
            "..........#SSSSSSSSSS#..........",
            "..........#SSS####SSS#..........",
            "..........####....####..........",
        ]
        let adult = [
            "................................",
            "........#..............#........",
            ".......#O#............#O#.......",
            ".......#S#............#S#.......",
            "......#OSO#..........#OSO#......",
            "......#SSS#.########.#SSS#......",
            ".....#OSSSL#LLLOOOOO#OSSSO#.....",
            "....#OSSSSSLLLLLOOOOOSSSSSO#....",
            "....####SSSLLLLLOOOOOSSS####....",
            "........#LLLLLLLOOOOOOO#........",
            ".......#LLLxLLLLOOOOxOOO#.......",
            ".......#LLLxxLLLOOOxxLOO#.......",
            ".......#LLxxxLLOOOOxxxOO#.......",
            ".......#OOxLxOOOOOOxLxOO#.......",
            ".......#OOOxOOOOOOOOxooo#..#....",
            "........#OOOOODDDOOOooo#..#o#...",
            "........#OOOOOODOOOoooo#..#o#...",
            ".........#OOOOODOOOooo#...#o#...",
            "..........#OOOOOOOOoo#...#ooo#..",
            ".........#OOOOOOOOOooo#...#o#...",
            ".........#OOOSSSSSSOoo#...#o#...",
            ".........#OOSSSSSSSSooo###oo#...",
            "........#OOOSSSSSSSSoooooOO#....",
            "........#OOSSSSSSSSSSooo####....",
            "........#OOSSSSSSSSSSoo#........",
            ".........#OSSSSdddSSSo#.........",
            ".........#OSSdddddddSo#.........",
            ".........#OSdddddddddo#.........",
            "..........#SSdddddddS#..........",
            ".........#SSSSSdddSSSS#.........",
            ".........#SSSS####SSSS#.........",
            ".........#####....#####.........",
        ]
        return assemble(id: "cat", nameZh: "小猫", base4: base4, stages: [
            ("baby", baby, Feat(mouthRow: 8, mouthCols: [7, 8], cheek: [(8, 4), (8, 11)], z: [(2, 13), (0, 13)], sweat: (4, 12)), sleepPose),
            ("child", child, Feat(mouthRow: 8, mouthCols: [7, 8], cheek: [(8, 3), (8, 12)], z: [(2, 14), (0, 14)], sweat: (4, 12)), sleepPose),
            ("adult", adult, Feat(mouthRow: 8, mouthCols: [7, 8], cheek: [(8, 3), (8, 12)], z: [(1, 14), (-1, 14)], sweat: (4, 12)), sleepPose),
        ])
    }
}
