import Foundation

extension PixelSpeciesCatalog {
    // MARK: - hamster 小仓鼠

    static func hamster() -> PixelSpeciesDef {
        let base4 = SpeciesBase4(body: 0xFFE7_B564, dark: 0xFFB0_7A3C, light: 0xFFFB_EBC8, accent: 0xFFF0_A87A)
        let baby = [
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            ".............######.............",
            "...........##OOOOOO##...........",
            ".........##LLLOOOOOOO##.........",
            "........#O^^LLLOOOOO^^O#........",
            "........#L^^LLLLOOOO^^O#........",
            ".......#LLLLLLLLLOOOOOOO#.......",
            ".......#LLLLLLLLLOOOOOOO#.......",
            ".......#LLwxLLLLLOOOwxOO#.......",
            "......#OOLxxLLLLOOooxxoOO#......",
            ".......#OOxxLLLSSSSoxxoo#.......",
            ".......#OOOLLLSSSSSSoooo#.......",
            ".......#OOOSSSSSSSSSSooo#.......",
            ".......#OOOSSS^^SSSSSooo#.......",
            ".......#OOSSSS^^SSSSSSoo#.......",
            ".......#OOSSSSSSSSSSSSoo#.......",
            "........#OSSSSSSSSSSSSo#........",
            "........#OOSSSddddSSSoo#........",
            ".........#Oddddddddddo#.........",
            "..........#dddddddddd#..........",
            ".........#Sdddd..ddddS#.........",
            ".........#SDSS#..#SSDS#.........",
            ".........##S##....##S##.........",
            "...........#........#...........",
            "................................",
            "................................",
            "................................",
        ]
        let child = [
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "........####........####........",
            "........#^^O########O^^#........",
            "........#^^LLLOOOOOOO^^#........",
            ".......#L^^LLLLLOOOOO^^O#.......",
            "......#OLLLLLLLLOOOOOOOOO#......",
            "......#LLLLLLLLLLOOOOOOOO#......",
            ".....#OLLLLLLLLLLOOOOOOOOO#.....",
            ".....#OLLLLLLLLLLOOOOOOOOO#.....",
            ".....#OOLwxLLLLLOOOOOwxOOO#.....",
            ".....#OOLxxLLLLLOOOOOxxOOO#.....",
            ".....#OOOxxLLLSSSSSooxxooO#.....",
            "......#OOOOOSSSSSSSSooooo#......",
            "......#OOOOSSSSSSSSSSoooo#......",
            ".......#OOSSSS^^SSSSSSoo#.......",
            "......#OOOSSSS^^SSSSSSooo#......",
            "......#OOOSSSSSSSSSSSSooo#......",
            "......#OOOSSSSSSSSSSSSooo#......",
            ".......#OOSSSSSSSSSSSSoo#.......",
            ".......#OOSSSSSSSSSSSSoo#.......",
            "........#OSSddddddddSSo#........",
            "........#OOddddddddddoo#........",
            ".........#OOddddddddoo#.........",
            ".........#.dddd..dddd.#.........",
            "........#SDSd##..##dSDS#........",
            ".........####......####.........",
            "................................",
            "................................",
        ]
        let adult = [
            "................................",
            "................................",
            "................................",
            ".......####..........####.......",
            "......#O^^O##########O^^O#......",
            "......#O^^OOOOOOOOOOOO^^O#......",
            ".......#^^LLLLLOOOOOOO^^#.......",
            "......#OLLLLLLLLOOOOOOOOO#......",
            ".....#OLLLLLLLLLLOOOOOOOOO#.....",
            ".....#OLLLLLLLLLLOOOOOOOOO#.....",
            "....#OOLLLLLLLLLLOOOOOOOOOO#....",
            "....#OOLLLLLLLLLLOOOOOOOOOO#....",
            "....#OOLLwxLLLLLLOOOOwxOOOO#....",
            "....#OOOLxxLLLLLOOOOOxxOOOO#....",
            "....#OOOOxxLLLLSSSSOoxxooOO#....",
            ".....#OOOOOOSSSSSSSSoooooo#.....",
            ".....#OOOOOSSSSSSSSSSooooo#.....",
            "......#OOOSSSS^^SSSSSSooo#......",
            "......#OOOSSSS^^SSSSSSooo#......",
            "......#OOSSSSSSSSSSSSSSoo#......",
            ".....#OOOSSSSSSSSSSSSSSooo#.....",
            "......#OOSSSSSSSSSSSSSSoo#......",
            "......#OOSSSSSSSSSSSSSSoo#......",
            "......#OOSSSSSSSSSSSSSSoo#......",
            "......#OOOSddddddddddSooo#......",
            ".......#OOddddddddddddoo#.......",
            "........#OOddddddddddoo#........",
            ".........#OOddddddddoo#.........",
            ".........#.dddd..dddd.#.........",
            "........#SDSS##..##SSDS#........",
            ".........####......####.........",
            "................................",
        ]
        return assemble(id: "hamster", nameZh: "小仓鼠", base4: base4, stages: [
            ("baby", baby, Feat(mouthRow: 10, mouthCols: [7, 8], cheek: [(6, 3), (6, 12), (7, 3), (7, 12)], z: [(3, 13), (1, 13)], sweat: (4, 13), pawL: (12, 4), pawR: (12, 11), feetRow: 14), nil),
            ("child", child, Feat(mouthRow: 10, mouthCols: [7, 8], cheek: [(6, 2), (6, 13), (7, 2), (7, 13)], z: [(3, 13), (1, 13)], sweat: (4, 13), pawL: (12, 4), pawR: (12, 11), feetRow: 14), nil),
            ("adult", adult, Feat(mouthRow: 9, mouthCols: [7, 8], cheek: [(6, 2), (6, 13), (7, 2), (7, 13)], z: [(2, 13), (0, 13)], sweat: (3, 13), pawL: (13, 4), pawR: (13, 11), feetRow: 15), nil),
        ])
    }
}
