import Foundation

extension PixelSpeciesCatalog {
    // MARK: - hamster 小仓鼠

    static func hamster() -> PixelSpeciesDef {
        let base4 = SpeciesBase4(body: 0xFFE7_B564, dark: 0xFFB0_7A3C, light: 0xFFFB_EBC8, accent: 0xFFF0_A87A)
        let baby = [
            "................................",
            "................................",
            "....oooo............oooo........",
            "....oooo............oooo........",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOO##wwww##OOOO##wwww##OOOO##",
            "##OOOO##wwww##OOOO##wwww##OOOO##",
            "##OOOO##wwxx##OOOO##xxww##OOOO##",
            "##OOOO##wwxx##OOOO##xxww##OOOO##",
            "##OOOOOOOOOOOO^^^^OOOOOOOOOOOO##",
            "##OOOOOOOOOOOO^^^^OOOOOOOOOOOO##",
            "##OOOOOO++++++++++++++++OOOOOO##",
            "##OOOOOO++++++++++++++++OOOOOO##",
            "..##OOOO++++++++++++++++OOOO##..",
            "..##OOOO++++++++++++++++OOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "......oooo##........##oooo......",
            "......oooo##........##oooo......",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let child = [
            "................................",
            "................................",
            "....oooo............oooo........",
            "....oooo............oooo........",
            "..ooOOOOOOOOOOOOOOOOOOOOOOOOoo..",
            "..ooOOOOOOOOOOOOOOOOOOOOOOOOoo..",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOO##wwww##OOOO##wwww##OOOO##",
            "##OOOO##wwww##OOOO##wwww##OOOO##",
            "##OOOO##wwxx##OOOO##xxww##OOOO##",
            "##OOOO##wwxx##OOOO##xxww##OOOO##",
            "##OOOOOOOOOOOO^^^^OOOOOOOOOOOO##",
            "##OOOOOOOOOOOO^^^^OOOOOOOOOOOO##",
            "##OOOOOO++++++++++++++++OOOOOO##",
            "##OOOOOO++++++++++++++++OOOOOO##",
            "##OOOOOO++++++++++++++++OOOOOO##",
            "##OOOOOO++++++++++++++++OOOOOO##",
            "..##OOOO++++++++++++++++OOOO##..",
            "..##OOOO++++++++++++++++OOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "......oooo##........##oooo......",
            "......oooo##........##oooo......",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let adult = [
            "....oooo............oooo........",
            "....oooo............oooo........",
            "..ooOOOOOOOOOOOOOOOOOOOOOOOOoo..",
            "..ooOOOOOOOOOOOOOOOOOOOOOOOOoo..",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOO##wwww##OOOO##wwww##OOOO##",
            "##OOOO##wwww##OOOO##wwww##OOOO##",
            "##OOOO##wwxx##OOOO##xxww##OOOO##",
            "##OOOO##wwxx##OOOO##xxww##OOOO##",
            "##OOOOOOOOOOOO^^^^OOOOOOOOOOOO##",
            "##OOOOOOOOOOOO^^^^OOOOOOOOOOOO##",
            "##OOOOOOOO++++++++++++OOOOOOOO##",
            "##OOOOOOOO++++++++++++OOOOOOOO##",
            "##OOOOOO++++++++++++++++OOOOOO##",
            "##OOOOOO++++++++++++++++OOOOOO##",
            "##OOOOOO++++++++++++++++OOOOOO##",
            "##OOOOOO++++++++++++++++OOOOOO##",
            "##OOOOOO++++++++++++++++OOOOOO##",
            "##OOOOOO++++++++++++++++OOOOOO##",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "....oooo##OOOO....OOOO##oooo....",
            "....oooo##OOOO....OOOO##oooo....",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        return assemble(id: "hamster", nameZh: "小仓鼠", base4: base4, stages: [
            ("baby", baby, Feat(mouthRow: 7, mouthCols: [6, 7, 8, 9], cheek: [(5, 1), (5, 14), (6, 1), (6, 14)], z: [(1, 13), (0, 14)], sweat: (1, 12)), nil),
            ("child", child, Feat(mouthRow: 7, mouthCols: [6, 7, 8, 9], cheek: [(5, 1), (5, 14), (6, 1), (6, 14)], z: [(1, 13), (0, 14)], sweat: (1, 12)), nil),
            ("adult", adult, Feat(mouthRow: 7, mouthCols: [6, 7, 8, 9], cheek: [(5, 1), (5, 14), (6, 1), (6, 14)], z: [(0, 13), (0, 14)], sweat: (1, 15)), nil),
        ])
    }
}
