import Foundation

extension PixelSpeciesCatalog {
    // MARK: - dragon 小龙

    static func dragon() -> PixelSpeciesDef {
        let base4 = SpeciesBase4(body: 0xFFB4_9BF0, dark: 0xFF84_68CE, light: 0xFFF6_E1A8, accent: 0xFFF6_E1A8)
        let baby = [
            "................................",
            "................................",
            "................................",
            "................................",
            "..........##....##..............",
            "..........##....##..............",
            "........####....####............",
            "........####....####............",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOO##wwww####wwww##OO##....",
            "..##OOOO##wwww####wwww##OO##....",
            "..##OOOO##wwxx####xxww##OO##....",
            "..##OOOO##wwxx####xxww##OO##....",
            "..##OOOOOOOO++oooo++OOOOOOOO##..",
            "..##OOOOOOOO++oooo++OOOOOOOO##..",
            "..##OOOOOO++++++++++++OOOOOO##..",
            "..##OOOOOO++++++++++++OOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "....##OOOOOOOOOOOOOOOO##oo......",
            "....##OOOOOOOOOOOOOOOO##oo......",
            "....##OOOOOOOOOOOOOOOO##oo......",
            "....##OOOOOOOOOOOOOOOO##oo......",
            "......################..........",
            "......################..........",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let child = [
            "................................",
            "................................",
            "................................",
            "................................",
            "........##........##............",
            "........##........##............",
            "......##^^##....##^^##..........",
            "......##^^##....##^^##..........",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "..ooOO##wwww##OOOO##wwww##OOoo..",
            "..ooOO##wwww##OOOO##wwww##OOoo..",
            "..##OO##wwxx##OOOO##xxww##OO##..",
            "..##OO##wwxx##OOOO##xxww##OO##..",
            "..##OOOOOOOO++oooo++OOOOOOOO##..",
            "..##OOOOOOOO++oooo++OOOOOOOO##..",
            "..##OOOO++++++++++++++++OOOO##..",
            "..##OOOO++++++++++++++++OOOO##..",
            "..##OOOO++++++++++++++++OOOO##..",
            "..##OOOO++++++++++++++++OOOO##..",
            "....##OOOO++++++++OOOO##oo......",
            "....##OOOO++++++++OOOO##oo......",
            "....##OOOOOOOOOOOOOOOO##oooo....",
            "....##OOOOOOOOOOOOOOOO##oooo....",
            "......################..oooo....",
            "......################..oooo....",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let adult = [
            "................................",
            "................................",
            "........##........##............",
            "........##........##............",
            "......##^^##....##^^##..........",
            "......##^^##....##^^##..........",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "..oo##OOOOOOOOOOOOOOOOOOOO##oo..",
            "..oo##OOOOOOOOOOOOOOOOOOOO##oo..",
            "oooo##OOwwwwOOOOOOOOwwwwOO##oooo",
            "oooo##OOwwwwOOOOOOOOwwwwOO##oooo",
            "oooo##OOwwxxOOOOOOOOxxwwOO##oooo",
            "oooo##OOwwxxOOOOOOOOxxwwOO##oooo",
            "..oo##OOOOOO++oooo++OOOOOO##oo..",
            "..oo##OOOOOO++oooo++OOOOOO##oo..",
            "..##OOOO++++++++++++++++OOOO##..",
            "..##OOOO++++++++++++++++OOOO##..",
            "..##OOOO++++++++++++++++OOOO##..",
            "..##OOOO++++++++++++++++OOOO##..",
            "..##OOOO++++++++++++++++OOOO##..",
            "..##OOOO++++++++++++++++OOOO##..",
            "....##OOOO++++++++OOOO##oo......",
            "....##OOOO++++++++OOOO##oo......",
            "....##OOOOOOOOOOOOOOOO##oooo....",
            "....##OOOOOOOOOOOOOOOO##oooo....",
            "......##OOOOOOOOOOOO##OOoooo....",
            "......##OOOOOOOOOOOO##OOoooo....",
            "........############....oooo....",
            "........############....oooo....",
            "................................",
            "................................",
        ]
        return assemble(id: "dragon", nameZh: "小龙", base4: base4, stages: [
            ("baby", baby, Feat(mouthRow: 8, mouthCols: [6, 7, 8, 9], cheek: [(8, 4), (8, 5), (8, 10), (8, 11)], z: [(3, 13), (1, 13)], sweat: (4, 12)), nil),
            ("child", child, Feat(mouthRow: 7, mouthCols: [6, 7, 8, 9], cheek: [(6, 2), (6, 13)], z: [(3, 13), (1, 13)], sweat: (4, 12)), nil),
            ("adult", adult, Feat(mouthRow: 7, mouthCols: [6, 7, 8, 9], cheek: [(7, 3), (7, 4), (7, 11), (7, 12)], z: [(2, 13), (0, 13)], sweat: (4, 12)), nil),
        ])
    }
}
