import Foundation

extension PixelSpeciesCatalog {
    // MARK: - dog 小狗

    static func dog() -> PixelSpeciesDef {
        let base4 = SpeciesBase4(body: 0xFFC8_965A, dark: 0xFF8A_5A34, light: 0xFFF3_E2C4, accent: 0xFF4A_3020)
        let baby = [
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            ".............######.............",
            "...........##LLLLOO##...........",
            "..........#LLLLLLOOOO#..........",
            "..........#LLLLLLOOOO#..........",
            ".........#LLLLLLLOOOOO#.........",
            ".........#LLxLLLLOOxLO#.........",
            ".........#LxxLLLOOOxxO#.........",
            "........#OLLLLLOOOOOoOO#........",
            ".......#OdOOOOOOOooooodo#.......",
            ".......#dddOOO^^^^oooddd#.......",
            ".......#dddOSSS^^SSSoddd#.......",
            ".......#dddOSSSDDSSSoddd#.......",
            ".......#OdOOSSDDDDSSoodo#.......",
            "........#O###SSSSSS###o#........",
            ".........#...#SSSS#...#.........",
            "............#OOOooo#............",
            "...........#OOOOOooo#...........",
            "..........#OOOOOOOOOo#..........",
            "..........#OOOOOOOOOO#..........",
            "..........#OOOOOOOOOO#..........",
            "...........#OOOOOOOO#...........",
            "............#OOOOOO#............",
            ".............######.............",
            "...........###....###...........",
            "..........#SSS#..#SSS#..........",
            "...........###....###...........",
            "................................",
        ]
        let child = [
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "............########............",
            "...........#LLLLOOOO#...........",
            "..........#LLLLLLOOOO#..........",
            "..........#LLLLLOOOOO#..........",
            ".......###LLxLLLOOOxLO###.......",
            "......#OOOLxxLLOOOOxxOOOO#......",
            "......#OdOOOLOOOOOooooodO#......",
            ".....#OdddOOOOOOOooooodddO#.....",
            ".....#OdddOOOS^^^^SooodddO#.....",
            ".....#OdddOOSSS^^SSSoodddo#.....",
            ".....#OdddOSSSSDDSSSSodddo#.....",
            ".....#Oddd##SSDDDDdS##dddoO#....",
            "......#Od#..#dddddd#..#dooOO#...",
            "......#OO#...#dddd#...#oo#OO#...",
            ".......##..##OOOooo##..##.#O#...",
            "..........#OOOOOOoooo#.....#....",
            "..........#OOOOOOOooo#..........",
            ".........#OOOOOOOOOOOO#.........",
            ".........#OOOOOOOOOOOO#.........",
            ".........#OOOOOOOOOOOO#.........",
            "..........#OOOOOOOOOO#..........",
            "..........#SOOOOOOOOS#..........",
            "..........#SSOOOOOOSS#..........",
            ".........#SSS######SSS#.........",
            "..........#S#......#S#..........",
            "...........#........#...........",
        ]
        let adult = [
            "................................",
            "................................",
            "................................",
            "................................",
            ".............######.............",
            "...........##LLLLOO##...........",
            "..........#LLLLLLOOOO#..........",
            ".........#LLLLLLLOOOOO#.........",
            "......##.#LLLLLLLOOOOO#.###.....",
            ".....#OO#LLLxLLLLOOxLOO#OOO#....",
            "....#OOdOLLxxLLLOOOxxOOOdOO#....",
            "....#OdddOLLLLLOOOOOOoOdddO#....",
            "....#OdddOOOOOOOOOooooodddOO#...",
            "....#OdddOOOOO^^^^ooooodddOO#...",
            "....#OdddOOOOSS^^SSoooodddoO#...",
            "....#OdddOOOSSSDDSSSooodddoO#...",
            "....#odddo#SSSDDDDSSS##dddoO#...",
            "....#oddd#.#SSdddddS#..dddooO#..",
            "....#oodo#..#dddddd#...#dooOO#..",
            ".....#oo#....#dddd#....#oooOO#..",
            "......##....#OOOooo#....###OO#..",
            "..........##OOOOOooo##.....###..",
            ".........#OOOOOOOOoooo#.........",
            ".........#OOOOOOOOOOOo#.........",
            ".........#OOOOOOOOOOOO#.........",
            "........#OOOOOOOOOOOOOO#........",
            ".........#OOOOOOOOOOOO#.........",
            ".........#OOOOOOOOOOOO#.........",
            ".........#SSSOOOOOOSSS#.........",
            ".........#SSSSOOOOSSSS#.........",
            ".........#SSSS####SSSS#.........",
            ".........#####....#####.........",
        ]
        return assemble(id: "dog", nameZh: "小狗", base4: base4, stages: [
            ("baby", baby, Feat(mouthRow: 9, mouthCols: [7, 8], cheek: [(9, 5), (9, 10)], z: [(2, 14), (0, 14)], sweat: (1, 12)), nil),
            ("child", child, Feat(mouthRow: 10, mouthCols: [7, 8], cheek: [(8, 4), (8, 11)], z: [(2, 14), (0, 14)], sweat: (1, 13)), nil),
            ("adult", adult, Feat(mouthRow: 9, mouthCols: [7, 8], cheek: [(7, 4), (7, 11)], z: [(2, 14), (0, 14)], sweat: (1, 13)), nil),
        ])
    }
}
