import Foundation

extension PixelSpeciesCatalog {
    // MARK: - frog 小青蛙

    static func frog() -> PixelSpeciesDef {
        let base4 = SpeciesBase4(body: 0xFF83_CE63, dark: 0xFF4E_9B3A, light: 0xFFE7_F3C0, accent: 0xFF4E_9B3A)
        let baby = [
            "................................",
            "................................",
            "........############............",
            "........############............",
            "......##OOOOOOOOOOOOOOOO##......",
            "......##OOOOOOOOOOOOOOOO##......",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "..##OOOO##wwww####wwww##OOOO##..",
            "..##OOOO##wwww####wwww##OOOO##..",
            "..##OOOO##wwxx####xxww##OOOO##..",
            "..##OOOO##wwxx####xxww##OOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOO++++++++++++OOOOOO##..",
            "..##OOOOOO++++++++++++OOOOOO##..",
            "..##OOOOOO++oooooooo++OOOOOO##..",
            "..##OOOOOO++oooooooo++OOOOOO##..",
            "..##OOOOOO++++++++++++OOOOOO##..",
            "..##OOOOOO++++++++++++OOOOOO##..",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "......oooo##....##oooo..........",
            "......oooo##....##oooo..........",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let child = [
            "................................",
            "................................",
            "......####........####..........",
            "......####........####..........",
            "....##wwww##....##wwww##........",
            "....##wwww##....##wwww##........",
            "....##wwxx##....##xxww##........",
            "....##wwxx##....##xxww##........",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOO++++++++++++++++OOOO##..",
            "..##OOOO++++++++++++++++OOOO##..",
            "..##OO++++oooooooooooo++++OO##..",
            "..##OO++++oooooooooooo++++OO##..",
            "..##OO++++++++++++++++++++OO##..",
            "..##OO++++++++++++++++++++OO##..",
            "..##OOOO++++++++++++++++OOOO##..",
            "..##OOOO++++++++++++++++OOOO##..",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "......oooo##....##oooo..........",
            "......oooo##....##oooo..........",
            "................................",
            "................................",
            "................................",
            "................................",
        ]
        let adult = [
            "................................",
            "................................",
            "......####............####......",
            "......####............####......",
            "....##wwww##........##wwww##....",
            "....##wwww##........##wwww##....",
            "....##wwxx##........##xxww##....",
            "....##wwxx##........##xxww##....",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "..##OOOOOOOOOOOOOOOOOOOOOOOO##..",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOOOOOOOOOOOOOOOOOOOOOOOOOO##",
            "##OOOO++++++++++++++++++++OOOO##",
            "##OOOO++++++++++++++++++++OOOO##",
            "##OO++++++oooooooooooo++++++OO##",
            "##OO++++++oooooooooooo++++++OO##",
            "##OO++++++++++++++++++++++++OO##",
            "##OO++++++++++++++++++++++++OO##",
            "##OOOO++++++++++++++++++++OOOO##",
            "##OOOO++++++++++++++++++++OOOO##",
            "..##OOOO++++++++++++++++OOOO##..",
            "..##OOOO++++++++++++++++OOOO##..",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "....##OOOOOOOOOOOOOOOOOOOO##....",
            "..oooo##oo........oo##oooo......",
            "..oooo##oo........oo##oooo......",
            "................................",
            "................................",
        ]
        return assemble(id: "frog", nameZh: "小青蛙", base4: base4, stages: [
            ("baby", baby, Feat(mouthRow: 9, mouthCols: [6, 7, 8, 9], cheek: [(7, 3), (7, 4), (7, 11), (7, 12)], z: [(2, 13), (0, 13)], sweat: (4, 12)), nil),
            ("child", child, Feat(mouthRow: 8, mouthCols: [5, 6, 7, 8, 9, 10], cheek: [(6, 3), (6, 4), (6, 10), (6, 11)], z: [(2, 13), (0, 13)], sweat: (3, 12)), nil),
            ("adult", adult, Feat(mouthRow: 8, mouthCols: [5, 6, 7, 8, 9, 10], cheek: [(6, 3), (6, 4), (6, 11), (6, 12)], z: [(3, 14), (1, 14)], sweat: (3, 13)), nil),
        ])
    }
}
